language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
env:
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT='-p core'
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT='-p consumer'
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT='-p provider -x :provider:pact-jvm-provider:signArchives -x :core:pact-jvm-core-model:signArchives -x :core:pact-jvm-core-matchers:signArchives -x :core:pact-jvm-core-pact-broker:signArchives -x :core:pact-jvm-core-support:signArchives'
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT='-p pact-specification-test'
script:
  - unset _JAVA_OPTIONS
  - ./gradlew --stacktrace --no-daemon $PROJECT build
install: true
