# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: false

build_script:
  - java -version
  - gradlew --stacktrace --no-daemon -i check -x :consumer:pact-jvm-consumer-junit:clojureTest -x :provider:pact-jvm-provider-lein:compileClojure

