name: Pact-JVM Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  latest_jdk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        module: [ core, consumer, provider, pact-specification-test ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - run: ./gradlew -v
    - name: Build with Gradle
      run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} build

  supported_jdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ core, consumer, provider, pact-specification-test ]
        jdk: [ 8, 9, 10, 11, 12 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - run: ./gradlew -v
      - run: env
      - name: Build with Gradle
        run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} build
